---
title: "oculina16s_communitycomp"
output: html_document
date: '2022-06-08'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup

```{r packages composition}
library(rlang)
library(stringr)
library(dplyr)
library(stats)
library(ggpubr)
library(vegan)
library(cowplot)
library(tidyverse)
#library(MCMC.OTU)
#install.packages("remotes")
#remotes::install_github("Jtrachsel/funfuns")
library("funfuns")
#BiocManager::install("microbiome")
#remotes::install_github("r-lib/rlang")
library(microbiome)
```


Read in data

```{r read in data}
setwd("~/oculina/data")
samdf <- read.csv("~/oculina/data/oculina16s_sampledata_symdens.csv",header=TRUE)
load("~/oculina/data/taxa2.Rdata")
#load("ps.clean.Rdata")
load("~/oculina/data/ps.rare.rev.Rdata")
#load("ps.rare.trim.Rdata")
#load("ps.trim.Rdata")
#ps.cleanest <- readRDS("phyloseq.cleanest.RDS")

```


Rename ASVs to be more informative

```{r rename ASVs}
tax <- as.data.frame(ps.rare@tax_table@.Data)
tax.clean <- data.frame(row.names = row.names(tax),
                        Kingdom = str_replace(tax[,1], "D_0__",""),
                        Phylum = str_replace(tax[,2], "D_1__",""),
                        Class = str_replace(tax[,3], "D_2__",""),
                        Order = str_replace(tax[,4], "D_3__",""),
                        Family = str_replace(tax[,5], "D_4__",""),
                        Genus = str_replace(tax[,6], "D_5__",""),
                        Species = str_replace(tax[,7], "D_6__",""),
                        stringsAsFactors = FALSE)
tax.clean[is.na(tax.clean)] <- ""


for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}
####### Fill holes in the tax table
tax.clean[is.na(tax.clean)] <- ""
for (i in 1:nrow(tax.clean)){
  if (tax.clean[i,2] == ""){
    kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
    tax.clean[i, 2:7] <- kingdom
  } else if (tax.clean[i,3] == ""){
    phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
    tax.clean[i, 3:7] <- phylum
  } else if (tax.clean[i,4] == ""){
    class <- paste("Class_", tax.clean[i,3], sep = "")
    tax.clean[i, 4:7] <- class
  } else if (tax.clean[i,5] == ""){
    order <- paste("Order_", tax.clean[i,4], sep = "")
    tax.clean[i, 5:7] <- order
  } else if (tax.clean[i,6] == ""){
    family <- paste("Family_", tax.clean[i,5], sep = "")
    tax.clean[i, 6:7] <- family
  } else if (tax.clean[i,7] == ""){
    tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
  }
}

tax_table(ps.rare) <- as.matrix(tax.clean)


```


### Stats

```{r adonis types}
set.seed(123)
seq.rare <- data.frame(otu_table(ps.rare))
dist.rare <- vegdist(seq.rare, method="bray")
samdf.rare <- data.frame(sample_data(ps.rare))
row.names(samdf.rare)==row.names(seq.rare)

adonis2(dist.rare ~ type, data=samdf.rare, permutations=999)
#         Df SumOfSqs      R2      F Pr(>F)    
#type      2   4.6321 0.17727 6.8947  0.001 ***
#Residual 64  21.4990 0.82273                  
#Total    66  26.1311 1.00000      


bet.all <- betadisper(dist.rare,samdf.rare$type)
plot(bet.all) # look very dif
bd <- betadisper(dist.rare, samdf.rare$type)
anova(bd) # sig dif in dispersion, but since the centroids clearly look very dif i'm inclined to access results above (helpful video explainer here: https://www.youtube.com/watch?v=oLf0EpMJ4yA&t=1370s&ab_channel=RiffomonasProject)
#          Df  Sum Sq  Mean Sq F value    Pr(>F)    
#Groups     2 0.49696 0.248478  65.475 3.313e-16 ***
#Residuals 64 0.24288 0.003795     
pairwise.adonis(seq.rare, factors = samdf.rare$type, permutations = 999) #all sig dif (p = 0.001)

pairwise.adonis(seq.rare, factors = samdf.rare$site, permutations = 999)
# NR vs CL and NR vs RI sig dif

bet.all <- betadisper(dist.rare,samdf.rare$season)
plot(bet.all) #overlap a fair amount
adonis2(dist.rare ~ season, data=samdf.rare, permutations=999)
#         Df SumOfSqs      R2      F Pr(>F)    
#season    1    0.961 0.03678 2.4817  0.001 ***
#Residual 65   25.170 0.96322                  
#Total    66   26.131 1.00000   

bd <- betadisper(dist.rare, samdf.rare$season)
anova(bd) # not very significant which means variation in both summer and fall similar, so result for adonis is probably legit

adonis2(dist.rare ~ site, data=samdf.rare, permutations=999)
#         Df SumOfSqs      R2      F Pr(>F)  
#site      2   1.1882 0.04547 1.5243  0.011 *
#Residual 64  24.9429 0.95453                
#Total    66  26.1311 1.00000 

bd <- betadisper(dist.rare, samdf.rare$site)
anova(bd) #ns


adonis2(dist.rare ~ type*season, data=samdf.rare, permutations=999)
#            Df SumOfSqs      R2      F Pr(>F)    
#type         2     8005 0.13432 5.2175  0.001 ***
#season       1     1738 0.02916 2.2650  0.001 ***
#type:season  2     3058 0.05131 1.9932  0.001 ***
#Residual    61    46795 0.78521                  
#Total       66    59595 1.00000 

adonis2(dist.rare ~ type+site, data=samdf.rare, permutations=999)
#          Df SumOfSqs      R2      F Pr(>F)    
#type       2     8005 0.13432 5.1449  0.001 ***
#site       2     2280 0.03826 1.4655  0.002 ** 
#type:site  4     4189 0.07029 1.3461  0.002 ** 
#Residual  58    45121 0.75713                  
#Total     66    59595 1.00000     

adonis2(dist.rare ~ type+season+site, data=samdf.rare, permutations=999)
#                 Df SumOfSqs      R2      F Pr(>F)    
#type              2     8005 0.13432 5.5102  0.001 ***
#season            1     1738 0.02916 2.3920  0.001 ***
#site              2     2122 0.03561 1.4608  0.003 ** 
#type:season       2     3056 0.05129 2.1039  0.001 ***
#type:site         4     3973 0.06666 1.3673  0.004 ** 
#season:site       1     1101 0.01847 1.5156  0.008 ** 
#type:season:site  2     1829 0.03069 1.2589  0.069 .  
#Residual         52    37771 0.63380                  
#Total            66    59595 1.00000                  


# order of terms matters for adonis... read more here https://stats.stackexchange.com/questions/312302/adonis-in-vegan-order-of-variables-non-nested-with-one-degree-of-freedom-for
```

```{r adonis type comparisons within sites}
# NR
ps.NR <- subset_samples(ps.rare,site=="NR")
seq.NR <- data.frame(otu_table(ps.NR))
dist.NR <- vegdist(seq.NR, method="bray")
samdf.NR <- data.frame(sample_data(ps.NR))
row.names(samdf.NR)==row.names(seq.NR)

pairwise.adonis(seq.NR, factors = samdf.NR$type, permutations = 999)

# RI
ps.RI <- subset_samples(ps.rare,site=="RI")
seq.RI <- data.frame(otu_table(ps.RI))
dist.RI <- vegdist(seq.RI, method="bray")
samdf.RI <- data.frame(sample_data(ps.RI))
row.names(samdf.RI)==row.names(seq.RI)

pairwise.adonis(seq.RI, factors = samdf.RI$type, permutations = 999)


# CL
ps.CL <- subset_samples(ps.rare,site=="CL")
seq.CL <- data.frame(otu_table(ps.CL))
dist.CL <- vegdist(seq.CL, method="bray")
samdf.CL <- data.frame(sample_data(ps.CL))
row.names(samdf.CL)==row.names(seq.CL)

pairwise.adonis(seq.CL, factors = samdf.CL$type, permutations = 999)
```

```{r adonis types within seasons}
# Summer
ps.summer <- subset_samples(ps.rare,season=="Summer")
seq.summer <- data.frame(otu_table(ps.summer))
dist.summer <- vegdist(seq.summer, method="bray")
samdf.summer <- data.frame(sample_data(ps.summer))
row.names(samdf.summer)==row.names(seq.summer)

pairwise.adonis(seq.summer, factors = samdf.summer$type, permutations = 999)

# Fall
ps.fall <- subset_samples(ps.rare,season=="Fall")
seq.fall <- data.frame(otu_table(ps.fall))
dist.fall <- vegdist(seq.fall, method="bray")
samdf.fall <- data.frame(sample_data(ps.fall))
row.names(samdf.fall)==row.names(seq.fall)

pairwise.adonis(seq.fall, factors = samdf.fall$type, permutations = 999)
```


```{r adonis seawater}
ps.sw <- subset_samples(ps.rare,type=="seawater")
seq.sw <- data.frame(otu_table(ps.sw))
dist.sw <- vegdist(seq.sw, method="bray")
samdf.sw <- data.frame(sample_data(ps.sw))
row.names(samdf.sw)==row.names(seq.sw)

#site
bet.all <- betadisper(dist.sw,samdf.sw$site)
adonis2(dist.sw ~ site, data=samdf.sw, permutations = 999) #ns
bd <- betadisper(dist.sw, samdf.sw$site)
anova(bd) #ns

#season
bet.all <- betadisper(dist.sw,samdf.sw$season)
adonis2(dist.sw ~ season, data=samdf.sw, permutations = 999) #sig (<0.01 **)
bd <- betadisper(dist.sw, samdf.sw$season)
anova(bd) #ns

```

```{r adonis sediment}
ps.sed <- subset_samples(ps.rare,type=="sediment")
seq.sed <- data.frame(otu_table(ps.sed))
dist.sed <- vegdist(seq.sed, method="bray")
samdf.sed <- data.frame(sample_data(ps.sed))
row.names(samdf.sed)==row.names(seq.sed)

#site
adonis2(dist.sed ~ site, data=samdf.sed, permutations = 999) #<0.1 .
bd <- betadisper(dist.sed, samdf.sed$site)
anova(bd) #ns

#season
adonis2(dist.sed ~ season, data=samdf.sed, permutations = 999) #sig (<0.01 **)
bd <- betadisper(dist.sed, samdf.sed$season)
anova(bd) #ns


```

```{r test for overlap in coral, sw, and sed at each site}
### NR
ps.rare.NR <- subset_samples(ps.rare,site=="NR")
seq.rare.NR <- data.frame(otu_table(ps.rare.NR))
dist.rare.NR <- vegdist(seq.rare.NR, method="bray")
samdf.rare.NR <- data.frame(sample_data(ps.rare.NR))
row.names(samdf.rare.NR)==row.names(seq.rare.NR)

adonis2(dist.rare.NR ~ type, data=samdf.rare.NR, permutations=999)  # 0.001

bet.all <- betadisper(dist.rare.NR,samdf.rare.NR$type)
plot(bet.all) # look very dif
bd <- betadisper(dist.rare.NR, samdf.rare.NR$type)
anova(bd) # <0.001 ***
pairwise.adonis(seq.rare.NR, factors = samdf.rare.NR$type, permutations = 999)
#                 pairs  F.Model        R2 p.value p.adjusted
#1    coral vs seawater 4.806540 0.2107527   0.001      0.001
#2    coral vs sediment 2.928864 0.1547300   0.001      0.001
#3 seawater vs sediment 5.807710 0.4206136   0.005      0.005


### RI
ps.rare.RI <- subset_samples(ps.rare,site=="RI")
seq.rare.RI <- data.frame(otu_table(ps.rare.RI))
dist.rare.RI <- vegdist(seq.rare.RI, method="bray")
samdf.rare.RI <- data.frame(sample_data(ps.rare.RI))
row.names(samdf.rare.RI)==row.names(seq.rare.RI)

adonis2(dist.rare.RI ~ type, data=samdf.rare.RI, permutations=999)  # 0.001

bet.all <- betadisper(dist.rare.RI,samdf.rare.RI$type)
plot(bet.all) # look very dif
bd <- betadisper(dist.rare.RI, samdf.rare.RI$type)
anova(bd) # <0.001 ***
pairwise.adonis(seq.rare.RI, factors = samdf.rare.RI$type, permutations = 999)

### CL
ps.rare.CL <- subset_samples(ps.rare,site=="CL")
seq.rare.CL <- data.frame(otu_table(ps.rare.CL))
dist.rare.CL <- vegdist(seq.rare.CL, method="bray")
samdf.rare.CL <- data.frame(sample_data(ps.rare.CL))
row.names(samdf.rare.CL)==row.names(seq.rare.CL)

adonis2(dist.rare.CL ~ type, data=samdf.rare.CL, permutations=999)  # 0.001

bet.all <- betadisper(dist.rare.CL,samdf.rare.CL$type)
plot(bet.all) # look very dif
bd <- betadisper(dist.rare.CL, samdf.rare.CL$type)
anova(bd) # <0.001 ***
pairwise.adonis(seq.rare.CL, factors = samdf.rare.CL$type, permutations = 999)


# two-way adonis should actually just do this for me...
adonis2(dist.rare ~ type*site, data=samdf.coral, permutations=999) 
```


```{r stats for coral}
ps.coral <- subset_samples(ps.rare,type=="coral")
seq.coral <- data.frame(otu_table(ps.coral))
dist.coral <- vegdist(seq.coral, method="bray")
samdf.coral <- data.frame(sample_data(ps.coral))
row.names(samdf.coral)==row.names(seq.coral)

adonis2(dist.coral ~ site, data=samdf.coral, permutations=999) #< 0.001 ***

pairwise.adonis(seq.coral, factors = samdf.coral$site, permutations = 999) #all sig dif
#NR vs RI (**), NR vs. CL (***), RI vs CL (**)


adonis2(dist.coral ~ season, data=samdf.coral, permutations=999) # < 0.001 ***     

adonis2(dist.coral ~ symbstate, data=samdf.coral, permutations=999) #ns

# will look at site and season as main effects as well as their interaction term
adonis2(dist.coral ~ site*season, data=samdf.coral, permutations=999)
#            Df SumOfSqs      R2      F Pr(>F)    
#site         2   1.5246 0.09979 2.2915  0.001 ***
#season       1   0.7769 0.05085 2.3353  0.002 ** 
#site:season  1   0.6676 0.04369 2.0067  0.005 ** 
#Residual    37  12.3089 0.80566                  
#Total       41  15.2780 1.00000    


# site * symbstate
adonis2(dist.coral ~ site*symbstate, data=samdf.coral, permutations=999) #only site sig (***)

# season * symbstate
adonis2(dist.coral ~ season*symbstate, data=samdf.coral, permutations=999) #only season sig (***)

adonis2(dist.coral ~ season*symbstate*site, data=samdf.coral, permutations=999) 
#                      Df SumOfSqs      R2      F Pr(>F)    
#season                 1     5253 0.04014 1.8552  0.001 ***
#symbstate              1     2929 0.02239 1.0346  0.265    
#site                   2     7344 0.05613 1.2969  0.001 ***
#season:symbstate       1     2904 0.02220 1.0258  0.393    
#season:site            1     4129 0.03156 1.4585  0.002 ** 
#symbstate:site         2     5951 0.04548 1.0509  0.217    
#season:symbstate:site  1     3241 0.02477 1.1448  0.117    
#Residual              35    99094 0.75734                  
#Total                 44   130846 1.00000   
# try with just NR and RI just to check
ps.coral.noCL <- subset_samples(ps.coral,site %in% c("NR","RI"))
seq.coral.noCL <- data.frame(otu_table(ps.coral.noCL))
dist.coral.noCL <- vegdist(seq.coral.noCL, method="euclidian")
samdf.coral.noCL <- data.frame(sample_data(ps.coral.noCL))
row.names(samdf.coral.noCL)==row.names(seq.coral.noCL)
adonis2(dist.coral.noCL ~ symbstate, data=samdf.coral.noCL, permutations=999) #not sig

### BETADISPER ###
# If you have uneven variation in your data, adonis might not be effective -- should check for variation in dispersion using betadisper

# CORAL - SITE
bet.all <- betadisper(dist.coral,samdf.coral$site) #Betadisper calculates the average distance of group members to the group centroid in multivariate space (generated by a distance matrix). ANOVA/Permutest then tests whether distances are significantly different between groups.
bet.all
#Average distance to median:
#   CL    NR    RI 
#43.23 54.10 51.07 

plot(bet.all) # p < 0.5 *
anova(bet.all)
# CORAL - SEASON
bet.all <- betadisper(dist.coral,samdf.coral$season)
plot(bet.all)
anova(bet.all) #ns

# CORAL - SYMB STATE
bet.all <- betadisper(dist.coral,samdf.coral$symbstate)
plot(bet.all)
anova(bet.all) #ns

# Excluding CL
bet.all <- betadisper(dist.coral.noCL,samdf.coral.noCL$symbstate)
plot(bet.all)
permutest(bet.all, pairwise = TRUE, permutations = 999) #ns

```


```{r calculate core abundance}
# calculating core abundances #
core.sqs <- tax_table(pseq.core)
core.sqs.ids <- row.names(core.sqs)
core.sqs.ids
ps.rare.trim.rel <- transform_sample_counts(ps.rare.trim, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.trim.rel))
tax.core <- tax_table(ps.rare.trim.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])
```

Composition stats
```{r composition stats}
seq.rare <- data.frame(otu_table(ps.rare))
dist.rare <- vegdist(seq.rare, method="bray")
samdf.rare <- data.frame(sample_data(ps.rare))
row.names(samdf.rare)==row.names(seq.rare)
ps.coral <- subset_samples(ps.rare,type=="coral")

# Merges ASVs that have the same taxonomy rank (Genus)
gp = tax_glom(ps.coral, taxrank = "Genus")

# Define group/condition type
site = levels(sample_data(gp)$site)[1] 

# Retrieve sample name of the defined type
sn = sample_names(sample_data(gp)[sample_data(gp)$site == "NR",])

# Calculate taxa sum of the selected samples
top5 = head(sort(rowSums(otu_table(gp)[,sn]), decreasing = TRUE), 5)

# Combine count and taxonomyTable
top5 = cbind(as.data.frame(tax_table(gp)[names(top5),]), Count = top5)
```

```{r core - coral}
pseq.core.coral <- core(ps.coral, detection = 0, prevalence = .5)
pseq.core.coral #11 taxa
#saving
#core.coral.tax <- data.frame(pseq.core.coral@tax_table)
#write.csv(core.coral.tax,"core.coral.tax.csv")
ps_glom <- tax_glom(pseq.core.coral, "Genus")
#ps0 <- transform_sample_counts(ps_glom, function(x) x / sum(x))
ps1 <- merge_samples(ps_glom, "site")
#ps2 <- transform_sample_counts(ps1, function(x) x / sum(x))
plot_bar(ps1, fill="Genus")+
  geom_bar(stat="identity")+
  theme_cowplot()+
  scale_fill_brewer(palette="BrBG")
#ggsave(file="core.bar.pdf",width=8)

```

```{r core - seawater}
ps.sw <- subset_samples(ps.rare,type=="seawater")
pseq.core.sw <- core(ps.sw, detection = 0, prevalence = .5)
pseq.core.sw #75 taxa?? wow
#saving
#core.sw.tax <- data.frame(pseq.core.sw@tax_table)
#write.csv(core.sw.tax,"core.sw.tax.csv")
ps_glom <- tax_glom(pseq.core.sw, "Genus")
#ps0 <- transform_sample_counts(ps_glom, function(x) x / sum(x))
ps1 <- merge_samples(ps_glom, "site")
#ps2 <- transform_sample_counts(ps1, function(x) x / sum(x))
plot_bar(ps1, fill="Genus")+
  geom_bar(stat="identity")+
  theme_cowplot()+
  scale_fill_brewer(palette="BrBG")
#ggsave(file="core.bar.pdf",width=8)


```

```{r coral most abundant taxa}
# To get stats about most abundant groups
# All coral:
ps.rare.coral.rel <- transform_sample_counts(ps.coral, function(x) x / sum(x))
seq.rare.coral.rel <- data.frame(otu_table(ps.rare.coral.rel))
tax.core.coral <- tax_table(ps.rare.coral.rel)
seq.core.coral <- seq.rare.coral.rel %>% select(c(core.coral.sqs.ids))
core.rel <- data.frame(colMeans(seq.core.coral))
total.rel <- data.frame(colMeans(seq.rare.coral.rel))
total.rel.coral.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.coral.rel.),,drop=FALSE])

total.rel.coral.ordered <- total.rel.coral.ordered %>% rownames_to_column("sq")
tax.core.coral <- tax.core.coral %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

coral.rel.tax <- left_join(total.rel.coral.ordered, tax.core.coral, by="sq", copy=TRUE)
head(coral.rel.tax)
#write.csv(coral.rel.tax,"coral.rel.tax.csv")


# Coral - NR
ps.coral.NR <- subset_samples(ps.coral,site=="NR")
#pseq.core.coral <- core(ps.coral, detection = 0, prevalence = .5)
core.sqs <- tax_table(pseq.core.coral)
core.sqs.ids <- row.names(core.sqs)

ps.rare.rel <- transform_sample_counts(ps.coral.NR, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.rel))
tax.core <- tax_table(ps.rare.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])

total.rel.ordered <- total.rel.ordered %>% rownames_to_column("sq")
tax.core <- tax.core %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

coral.NR.rel.tax <- left_join(total.rel.ordered, tax.core, by="sq", copy=TRUE)
head(coral.NR.rel.tax)
#write.csv(coral.NR.rel.tax,"coral.NR.rel.tax.csv")

# Coral - RI
ps.coral.RI <- subset_samples(ps.coral,site=="RI")
#pseq.core.coral <- core(ps.coral, detection = 0, prevalence = .5)
core.sqs <- tax_table(pseq.core.coral)
core.sqs.ids <- row.names(core.sqs)

ps.rare.rel <- transform_sample_counts(ps.coral.RI, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.rel))
tax.core <- tax_table(ps.rare.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])

total.rel.ordered <- total.rel.ordered %>% rownames_to_column("sq")
tax.core <- tax.core %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

coral.RI.rel.tax <- left_join(total.rel.ordered, tax.core, by="sq", copy=TRUE)
head(coral.RI.rel.tax)
#write.csv(coral.RI.rel.tax,"coral.RI.rel.tax.csv")

# Coral - CL
ps.coral.CL <- subset_samples(ps.coral,site=="CL")
#pseq.core.coral <- core(ps.coral, detection = 0, prevalence = .5)
core.sqs <- tax_table(pseq.core.coral)
core.sqs.ids <- row.names(core.sqs)

ps.rare.rel <- transform_sample_counts(ps.coral.CL, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.rel))
tax.core <- tax_table(ps.rare.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])

total.rel.ordered <- total.rel.ordered %>% rownames_to_column("sq")
tax.core <- tax.core %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

coral.CL.rel.tax <- left_join(total.rel.ordered, tax.core, by="sq", copy=TRUE)
head(coral.CL.rel.tax)
#write.csv(coral.CL.rel.tax,"coral.CL.rel.tax.csv")
```

```{r}
# Seawater:
ps.sw <- subset_samples(ps.sw,type=="seawater")
pseq.core.sw <- core(ps.sw, detection = 0, prevalence = .5)
core.sqs <- tax_table(pseq.core.sw)
core.sqs.ids <- row.names(core.sqs)

ps.rare.rel <- transform_sample_counts(ps.sw, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.rel))
tax.core <- tax_table(ps.rare.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])

total.rel.ordered <- total.rel.ordered %>% rownames_to_column("sq")
tax.core <- tax.core %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

sw.rel.tax <- left_join(total.rel.ordered, tax.core, by="sq", copy=TRUE)
head(sw.rel.tax)
#write.csv(sw.rel.tax,"sw.rel.tax.csv")

# Sediment:
ps.sed <- subset_samples(ps.sed,type=="sediment")
pseq.core.sed <- core(ps.sed, detection = 0, prevalence = .5)
core.sqs <- tax_table(pseq.core.sed)
core.sqs.ids <- row.names(core.sqs)

ps.rare.rel <- transform_sample_counts(ps.sed, function(x) x / sum(x))
seq.rare.rel <- data.frame(otu_table(ps.rare.rel))
tax.core <- tax_table(ps.rare.rel)
seq.core <- seq.rare.rel %>% select(c(core.sqs.ids))
core.rel <- data.frame(colMeans(seq.core))
total.rel <- data.frame(colMeans(seq.rare.rel))
total.rel.ordered <- data.frame(total.rel[order(-total.rel$colMeans.seq.rare.rel.),,drop=FALSE])

total.rel.ordered <- total.rel.ordered %>% rownames_to_column("sq")
tax.core <- tax.core %>% as("matrix") %>% subset(select = colSums(!is.na(.)) > 0) %>% as_tibble(rownames = "sq") -> taxon.tbl

sed.rel.tax <- left_join(total.rel.ordered, tax.core, by="sq", copy=TRUE)
head(sed.rel.tax)
#write.csv(sed.rel.tax,"sed.rel.tax.csv")

```


```{r calculate coral core abundance for all samples}
# calculating core abundances #
ps.coral <- subset_samples(ps.rare,type=="coral")
pseq.core.coral <- core(ps.coral, detection = 0, prevalence = .5)
pseq.core.coral #11 taxa

#saving
#core.coral.tax <- data.frame(pseq.core.coral@tax_table)
#write.csv(core.coral.tax,"core.coral.tax.csv")
ps_glom <- tax_glom(pseq.core.coral, "Genus")
#ps0 <- transform_sample_counts(ps_glom, function(x) x / sum(x))
ps1 <- merge_samples(ps_glom, "site")
#ps2 <- transform_sample_counts(ps1, function(x) x / sum(x))
plot_bar(ps1, fill="Genus")+
  geom_bar(stat="identity")+
  theme_cowplot()+
  scale_fill_brewer(palette="BrBG")
#ggsave(file="core.bar.pdf",width=8)
```

```{r core - seawater}
ps.sed <- subset_samples(ps.rare,type=="sediment")
pseq.core.sed <- core(ps.sed, detection = 0, prevalence = .5)
pseq.core.sed #29 taxa
#saving
#core.sed.tax <- data.frame(pseq.core.sed@tax_table)
#write.csv(core.sed.tax,"core.sed.tax.csv")
ps_glom <- tax_glom(pseq.core.sed, "Genus")
#ps0 <- transform_sample_counts(ps_glom, function(x) x / sum(x))
ps1 <- merge_samples(ps_glom, "site")
#ps2 <- transform_sample_counts(ps1, function(x) x / sum(x))
plot_bar(ps1, fill="Genus")+
  geom_bar(stat="identity")+
  theme_cowplot()+
  scale_fill_brewer(palette="BrBG")
#ggsave(file="core.bar.pdf",width=8)


```
```{r bubble plot}
library("reshape2")
library("stringr")
library("ggplot2")
library("RColorBrewer")

#setwd("~/oculina_old/setup/tax")
OTU = read.table("ASVtable.txt", header=TRUE, sep="\t", row.names = 1)
RAtab <- sweep(OTU,1,rowSums(OTU),"/")
#write.csv(RAtab, "ASVtablePercent.csv") #uncomment this to write out your new ASV table
#row sums before
rowSums(OTU)
#check row sums after-- should be 1 for all samples
rowSums(RAtab)


```

