---
title: "oculina16s_pcoa"
output: html_document
date: '2022-08-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(vegan)

#setwd("~/oculina/data")
load("ps.rare.rev.Rdata")
```


Rename ASVs to be more informative

```{r rename ASVs}
tax <- as.data.frame(ps.rare@tax_table@.Data)
tax.clean <- data.frame(row.names = row.names(tax),
                        Kingdom = str_replace(tax[,1], "D_0__",""),
                        Phylum = str_replace(tax[,2], "D_1__",""),
                        Class = str_replace(tax[,3], "D_2__",""),
                        Order = str_replace(tax[,4], "D_3__",""),
                        Family = str_replace(tax[,5], "D_4__",""),
                        Genus = str_replace(tax[,6], "D_5__",""),
                        Species = str_replace(tax[,7], "D_6__",""),
                        stringsAsFactors = FALSE)
tax.clean[is.na(tax.clean)] <- ""


for (i in 1:7){ tax.clean[,i] <- as.character(tax.clean[,i])}
####### Fill holes in the tax table
tax.clean[is.na(tax.clean)] <- ""
for (i in 1:nrow(tax.clean)){
  if (tax.clean[i,2] == ""){
    kingdom <- paste("Kingdom_", tax.clean[i,1], sep = "")
    tax.clean[i, 2:7] <- kingdom
  } else if (tax.clean[i,3] == ""){
    phylum <- paste("Phylum_", tax.clean[i,2], sep = "")
    tax.clean[i, 3:7] <- phylum
  } else if (tax.clean[i,4] == ""){
    class <- paste("Class_", tax.clean[i,3], sep = "")
    tax.clean[i, 4:7] <- class
  } else if (tax.clean[i,5] == ""){
    order <- paste("Order_", tax.clean[i,4], sep = "")
    tax.clean[i, 5:7] <- order
  } else if (tax.clean[i,6] == ""){
    family <- paste("Family_", tax.clean[i,5], sep = "")
    tax.clean[i, 6:7] <- family
  } else if (tax.clean[i,7] == ""){
    tax.clean$Species[i] <- paste("Genus",tax.clean$Genus[i], sep = "_")
  }
}

tax_table(ps.rare) <- as.matrix(tax.clean)

# subset coral
ps.coral <- subset_samples(ps.rare,type=="coral")

#convert density to numeric
sample_data(ps.coral)$density <- as.numeric(sample_data(ps.coral)$density)
```


```{r PCoA plots}
# by site
pcoa.coral.site <- plot_ordination(ps.coral, ordinate(ps.coral,"PCoA", "bray"),color="site", shape="site")+
  stat_ellipse()+
  theme_cowplot()+
  scale_color_manual(name="Site",values=c("darkslategray3","darkslategray4","#000004"))+
  scale_shape_manual(name="Site",values=c(8,4,9))+
  #xlab("Axis 1 (40.5%)")+
  #ylab("Axis 2 (19%)")+
  ggtitle("Rarefied (Coral)")

pcoa.coral.season <- plot_ordination(ps.coral, ordinate(ps.coral,"PCoA", "bray"),color="season", shape="season")+
  stat_ellipse()+
  theme_cowplot()+
  scale_color_manual(name="Season",values=c("darkorchid4","goldenrod1"))+
  scale_shape_manual(name="Season",values=c(8,4))+
  #xlab("Axis 1 (40.5%)")+
  #ylab("Axis 2 (19%)")+
  ggtitle("Rarefied (Coral)")

pcoa.coral.ss <- plot_ordination(ps.coral, ordinate(ps.coral,"PCoA", "bray"),color="symbstate", shape="symbstate")+
  stat_ellipse()+
  theme_cowplot()+
  scale_colour_manual(name="Symbiotic State",values=c("lightcyan3","coral4"),labels=c("Aposymbiotic","Symbiotic")) +
  scale_shape_manual(name="Symbiotic State",values=c(8,4),labels=c("Aposymbiotic","Symbiotic"))+
 # xlab("Axis 1 (40.5%)")+
 # ylab("Axis 2 (19%)")+
  ggtitle("Rarefied (Coral)")

pcoa.coral.season.all <- plot_ordination(ps.coral,ordinate(ps.coral,"PCoA", "bray"),color="season", shape="season")+
  stat_ellipse()+
  theme_cowplot()+
  scale_colour_manual(name="Season", values=c("#8405A7FF","#ED7953FF"))+
  scale_shape_manual(name="Season",values=c(8,4))+
  #xlab("Axis 1 (40.5%)")+
 # ylab("Axis 2 (19%)")+
  ggtitle("Rarefied (Coral)")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

pcoa.coral.ss.all <- plot_ordination(ps.coral,ordinate(ps.coral,"PCoA", "bray"),color="symbstate",shape="symbstate")+
  stat_ellipse()+
  theme_cowplot()+
  scale_colour_manual(name="Symbiotic State",values=c("lightcyan3","coral4"),labels=c("Aposymbiotic","Symbiotic")) +
  scale_shape_manual(name="Symbiotic State",values=c(8,4),labels=c("Aposymbiotic","Symbiotic"))+
  #xlab("Axis 1 (40.5%)")+
 # ylab("Axis 2 (19%)")+
  ggtitle("Rarefied (Coral)")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

pcoa.alltypes <- plot_ordination(ps.rare,ordinate(ps.rare,"PCoA", "bray"),color="type", shape="type")+
  stat_ellipse()+
  theme_cowplot()+
  scale_color_manual(name="Type",values=c("bisque2","paleturquoise3","chocolate4"))+
  scale_shape_manual(name="Type",values=c(8,4,9))+
  #xlab("Axis 1 (25.8%)")+
  #ylab("Axis 2 (22.5%)")+
  ggtitle("Rarefied (Coral)")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

pcoa.coral.sd <- plot_ordination(ps.coral, ordinate(ps.coral,"PCoA", "bray"), color="density")+
 # stat_ellipse()+
  theme_cowplot()+
  geom_point(size=3)+
  scale_color_continuous(high = "#132B43", low = "#CFEDF6")+
 # scale_colour_manual(name="Symbiotic State",values=c("lightcyan3","coral4"),labels=c("Aposymbiotic","Symbiotic")) +
  ggtitle("Rarefied (Coral)")

#ggsave(pcoa.coral.site,file="./figures/pcoa.coral.site.pdf",width=8,height=4)
#ggsave(pcoa.coral.season,file="./figures/pcoa.coral.season.pdf",width=8,height=4)
#ggsave(pcoa.coral.ss,file="./figures/pcoa.coral.ss.pdf",width=8,height=4)
#ggsave(pcoa.coral.season.all,file="./figures/pcoa.coral.season.all.pdf",width=8,height=4)
#ggsave(pcoa.coral.ss.all,file="./figures/pcoa.coral.ss.all.pdf",width=9,height=5)
#ggsave(pcoa.alltypes,file="./figures/pcoa.alltypes.pdf",width=9,height=5)
#ggsave(pcoa.coral.sd,file="./figures/pcoa.coral.sd.pdf",width=9,height=5)

```

