---
title: "oculina16s_analysis"
output:
  word_document: default
  html_document: default
  pdf_document: default
date: '2022-06-01'
editor_options: 
  chunk_output_type: console
---
### Based on DADA2 Pipeline 1.16 Walkthrough & Nicola Kriefall's Moorea holobiont analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Packages
```{r packages}
library(ggplot2)
library(cowplot)
library(phyloseq)
library(car)
library(ggpubr)
library(vegan)
library(dada2)
library(ggpmisc)

```

## Read in data

```{r read in data}
#setwd("~/oculina/data/")
samdf <- read.csv("~/oculina/data/oculina16s_sampledata_symdens.csv",header=TRUE) 
row.names(samdf) <- samdf$id
load("~/oculina/data/taxa2.rev.Rdata")
```


```{r read in ps objects}
seqtab.less <- read.csv("~/oculina/data/oculina16s_rev_seqtab.less",row.names=1)
load("~/oculina/data/ps.less_rev.Rdata")
ps.less #7005 taxa, 71 samples
```

# Diversity

[Notes from phyloseq author](https://rdrr.io/bioc/phyloseq/man/estimate_richness.html)
Visualize alpha-diversity - Should be done on raw, untrimmed dataset

```{r generate div metrics}
df <- data.frame(estimate_richness(ps.less, split=TRUE, measures=c("Shannon","InvSimpson","Simpson","Observed","Chao1")))

#library(mia)

df$id <- rownames(df)
df.div <- merge(df,samdf,by="id") #add sample data
df.div$density <- as.numeric(df.div$density)
#shannon diversity divided by species richness
df.div$even <- df.div$Shannon/(log(df.div$Observed))
df.div.NR <- subset(df.div,site=="NR")
df.div.RI <- subset(df.div,site=="RI")
df.div.CL <- subset(df.div,site=="CL")
df.div.summer <- subset(df.div,season=="Summer")
df.div.fall <- subset(df.div,season=="Fall")
df.div.coral <- subset(df.div, type=="coral")
df.div.ss <- subset(df.div, type=="sediment" | type =="seawater")
df.div.coral.NR <- subset(df.div.coral,site=="NR")
df.div.coral.RI <- subset(df.div.coral,site=="RI")
df.div.coral.CL <- subset(df.div.coral,site=="CL")
df.div.coral.NR.RI <- subset(df.div.coral,site %in% c("NR","RI"))


```


### Shannon

```{r shannon}
#reorder summer and fall
df.div.coral$season <- as.character(df.div.coral$season)
df.div.coral$season <- factor(df.div.coral$season, levels=c("Summer","Fall"))

#reorder sites
df.div.coral$site <- as.character(df.div.coral$site)
df.div.coral$site <- factor(df.div.coral$site, levels=c("NR","RI","CL"))

#all types
gg.sha.alltypes <- ggplot(df.div,aes(x=type,y=Shannon,color=type,group=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(position="jitter", size=2, alpha=0.4)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","Seawater","Sediment"))+
  #geom_jitter(alpha=0.5)+
  ylab("Shannon Index")+
  labs(x=NULL)+
  theme_cowplot()+
  theme(legend.position="none")

gg.sha.site.alltypes <-ggplot(df.div,aes(x=type,y=Shannon,color=type,group=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(position="jitter", size=2, alpha=0.4)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","SW","Sed."))+
  #geom_jitter(alpha=0.5)+
  ylab("Shannon Index")+
  labs(x=NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

gg.sha.seas.alltypes <-ggplot(df.div,aes(x=type,y=Shannon,color=type,group=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(position=position_jitter(width=0.1), size=2, alpha=0.4)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","SW","Sed."))+
  geom_jitter(alpha=0.5)+
  ylab("Shannon index")+
  labs(x=NULL)+
  theme_cowplot()+ 
  theme(legend.position="none")+
  facet_wrap(~forcats::fct_relevel(season, "Summer","Fall"))

#setwd("~/oculina/diversity")
#ggsave(gg.sha.alltypes,file="./figures/gg.sha.alltypes.png",width=8,height=4)
#ggsave(gg.sha.site.alltypes,file="./figures/gg.sha.site.alltypes.png",width=8,height=4)
#ggsave(gg.sha.seas.alltypes,file="./figures/gg.sha.seas.alltypes.png",width=8,height=4)

### Observed
gg.obs.alltypes <- ggplot(df.div,aes(x=type,y=Observed,color=type,group=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(position="jitter", size=2, alpha=0.4)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","Seawater","Sediment"))+
  #geom_jitter(alpha=0.5)+
  ylab("ASV Richness")+
  labs(x=NULL)+
  theme_cowplot()+
  theme(legend.position="none")

#ggsave(gg.obs.alltypes,file="./figures/gg.obs.alltypes.png",width=8,height=4)


### Coral only

gg.sha.coral.site.ss <- ggplot(df.div.coral,aes(x=site,y=Shannon,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1,19))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.03),size=3, alpha=0.5,aes(shape=symbstate,group=symbstate))+
  ylab("Shannon Index")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Shannon Index (Coral)")+
  guides(shape=guide_legend("Symbiotic State"),
         color="none")

gg.sha.coral.site.seas <- ggplot(df.div.coral,aes(x=site,y=Shannon,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(8,17))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.02),size=3, alpha=0.5,aes(shape=season,group=season))+
  ylab("Shannon Index")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Shannon Index (Coral)")+
  guides(shape=guide_legend("Season"),
         color="none")


gg.sha.coral.symb <- ggplot(df.div.coral,aes(x=symbstate,y=Shannon,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("lightcyan3","coral4"))+
  geom_jitter(alpha=0.5)+
  ylab("Shannon index")+
  scale_x_discrete(name = NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.sha.coral.seas <- ggplot(df.div.coral,aes(x=season,y=Shannon,color=season))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=1),size=3, alpha=0.5,aes(shape=season,group=season))+
  ylab("Shannon index")+
  xlab("Season")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.sha.coral.sd <- ggplot(df.div.coral,aes(x=density,y=Shannon, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Shannon index")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")

gg.sha.coral.sd.sqrt <- ggplot(df.div.coral,aes(x=density_sqrt,y=Shannon, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(10, 19))+
  theme_cowplot()+
  xlab(expression(sqrt(Density (cells/cm2))))+
  ylab("Shannon index")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")

#library(ggpmisc)
gg.sha.coral.sd <- gg.sha.coral.sd + stat_poly_eq(label.x = "right")
gg.sha.coral.sd.sqrt <- gg.sha.coral.sd.sqrt + stat_poly_eq(label.x = "right")

gg.sha.coral.sd.overall <- ggplot(df.div.coral,aes(x=density_sqrt,y=Shannon))+
  geom_point(size=3, aes(shape=symbstate,color=site))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Shannon Index")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid", color="red")+
  stat_poly_eq(label.x = "right")+
  ggtitle("Shannon Index (Coral)")

#other viz for sd
gg.sha.coral.sd <- ggplot(df.div.coral,aes(x=density,y=Shannon, color=site))+
  geom_point(size=3, alpha=0.8, aes(shape=symbstate))+
  scale_color_manual(values=c("#E3C6A3", "#B07631"))+
  scale_shape_manual(values=c(7, 8, 16))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Shannon index")+
  labs(color="Symbiotic state",shape="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE)

gg.sha.coral.ss.site <- ggplot(df.div.coral,aes(x=site,y=Shannon,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("Shannon Index")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")


#ggsave(gg.sha.coral.site.ss,file="./figures/gg.sha.coral.site.ss.png",width=8,height=4)
#ggsave(gg.sha.coral.site.seas,file="./figures/gg.sha.coral.site.seas.png",width=8,height=4)
#ggsave(gg.sha.coral.symb,file="./figures/gg.sha.coral.symb.pdf",width=8,height=4)
#ggsave(gg.sha.coral.seas,file="./figures/gg.sha.coral.seas.png",width=8,height=4)
#ggsave(gg.sha.coral.sd,file="./figures/gg.sha.coral.sd.png",width=8,height=4)
#ggsave(gg.sha.coral.sd.sqrt,file="./figures/gg.sha.coral.sd.sqrt.png",width=8,height=4)
#ggsave(gg.sha.coral.ss.site,file="./figures/gg.sha.coral.ss.site.png",width=8,height=4)

```



```{r shannon sedsw}
#plotting sed and sw
gg.sedsw <- ggplot(df.div.ss, aes(x=season,y=Shannon,color=season))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(shape=type), size = 3, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  xlab("Season")+
  ylab("Shannon index")+
  #scale_x_discrete(labels=c("Fall","Summer"))+
  scale_colour_manual(values=c("#ED7953FF","#8405A7FF"))+
  theme_cowplot()+
  guides(color = "none")+
  labs(shape = "Type")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

gg.sedsw
```

```{r shannon season and site}

gg.shannon.summer <- ggplot(df.div.summer, aes(x=site,y=Shannon,color=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=type), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("darksalmon","paleturquoise3","chocolate4")) +
  ylab("Shannon Index")+
  xlab("Site")+
  #labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL')) +
  theme(legend.position="none")+
  ylim(min_value=0, max_value=6.5)+
  ggtitle("a) Summer")

gg.shannon.fall <- ggplot(df.div.fall, aes(x=site,y=Shannon,color=type))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=type), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(name="Type",values=c("darksalmon","paleturquoise3","chocolate4"), labels=c("Coral","Seawater","Sediment")) +
  ylab("Shannon Index")+
  xlab("Site")+
  #labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI'))+
  ylim(min_value=0, max_value=6.5)+
  ggtitle("b) Fall")

plot_grid(gg.shannon.summer, gg.shannon.fall, axis="bt",align="hv")
```


### Inv Simpson

```{r}
gg.invsim.coral.site.seas <- ggplot(df.div.coral,aes(x=site,y=InvSimpson,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(8,17))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.02),size=3, alpha=0.5,aes(shape=season,group=season))+
  ylab("Inverse Simpson Index")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Inverse Simpson (Coral)")+
  guides(shape=guide_legend("Season"),
         color="none")

gg.invsim.coral.ss.site <- ggplot(df.div.coral,aes(x=site,y=InvSimpson,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("Inverse Simpson Index")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Inverse Simpson (Coral)")
  #theme(legend.position="none")


gg.invsim.coral.sd <- ggplot(df.div.coral,aes(x=density,y=InvSimpson, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Inverse Simpson index")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")+
  ggtitle("Inverse Simpson (Coral)")+
    stat_poly_eq(label.x = "right")



#ggsave(gg.invsim.coral.site.seas,file="./figures/gg.invsim.coral.site.seas.png",width=8,height=4)
#ggsave(gg.invsim.coral.ss.site,file="./figures/gg.invsim.coral.ss.site.png",width=8,height=4)
#ggsave(gg.invsim.coral.sd,file="./figures/gg.invsim.coral.sd.png",width=8,height=4)

```

### Simpson

```{r simpson coral}


gg.sim.coral.site.ss <- ggplot(df.div.coral,aes(x=site,y=Simpson,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1,19))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.03),size=3, alpha=0.5,aes(shape=symbstate,group=symbstate))+
  ylab("Shannon Index")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Shannon Index (Coral)")+
  guides(shape=guide_legend("Symbiotic State"),
         color="none")

gg.sim.coral.site.seas <- ggplot(df.div.coral,aes(x=site,y=Simpson,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(8,17))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.02),size=3, alpha=0.5,aes(shape=season,group=season))+
  ylab("Shannon Index")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Shannon Index (Coral)")+
  guides(shape=guide_legend("Season"),
         color="none")

gg.sim.coral.site <- ggplot(df.div.coral,aes(x=site,y=Simpson,color=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darkslategray3","darkslategray4","#000004"))+
  geom_jitter(alpha=0.5)+
  ylab("Simpson index")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.sim.coral.seas <- ggplot(df.div.coral,aes(x=season,y=Simpson,color=season))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  geom_jitter(alpha=0.5)+
  ylab("Simpson index")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.sim.coral.ss <- ggplot(df.div.coral,aes(x=symbstate,y=Simpson,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("lightcyan3","coral4"))+
  geom_jitter(alpha=0.5)+
  ylab("Simpson index")+
  scale_x_discrete(name = NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.sim.coral.sd <- ggplot(df.div.coral,aes(x=density,y=Simpson,color=density))+
  geom_point(size=3, alpha=0.8)+
  scale_color_continuous(high = "#132B43", low = "#6DCDFB")+
  theme_cowplot()+
  xlab("Density")+
  ylab("Simpson index")+
  labs(color="Density")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

gg.sim.coral.ss.site <- ggplot(df.div.coral,aes(x=site,y=Shannon,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("Simpson Index")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")

#ggsave(gg.sim.coral.site,file="./figures/gg.sim.coral.site.pdf",width=8,height=4)
#ggsave(gg.sim.coral.seas,file="./figures/gg.sim.coral.seas.pdf",width=8,height=4)
#ggsave(gg.sim.coral.ss,file="./figures/gg.sim.coral.ss.pdf",width=8,height=4)
#ggsave(gg.sim.coral.sd,file="./figures/gg.sim.coral.sd.pdf",width=8,height=4)
#ggsave(gg.sim.coral.ss.site,file="./figures/gg.sim.coral.ss.site.pdf",width=8,height=4)

```

### Evenness
```{r}
gg.even.coral.sd <- ggplot(df.div.coral,aes(x=density,y=even, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Evenness")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")+
  ggtitle("Evenness (Coral)")+
    stat_poly_eq(label.x = "right")

```

```{r richness coral}

gg.obs.coral.site.ss <- ggplot(df.div.coral,aes(x=site,y=Observed,color=site,group=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1,19))+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=0.03),size=3, alpha=0.5,aes(shape=symbstate,group=symbstate))+
  ylab("Observed OTUs")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Richness (Coral)")+
  guides(shape=guide_legend("Symbiotic State"),
         color="none")

gg.obs.coral.site.seas <- ggplot(df.div.coral,aes(x=site,y=Observed,color=season))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=season), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  ylab("ASV richness")+
  xlab("Site")+
  labs(color = "Season")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")


gg.obs.coral.sd <- ggplot(df.div.coral,aes(x=density,y=Observed, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Observed OTUs")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")+
  stat_poly_eq(label.x = "right")+
  ggtitle("Richness (Coral)")

gg.obs.coral.sd.sqrt <- ggplot(df.div.coral,aes(x=density_sqrt,y=Observed, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(10, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Observed OTUs")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")+
  stat_poly_eq(label.x = "right")+
  ggtitle("Richness (Coral)")

#overall trend, not by site
gg.obs.coral.sd.overall <- ggplot(df.div.coral,aes(x=density,y=Observed))+
  geom_point(size=3, aes(shape=symbstate,color=site))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(1, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Observed OTUs")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid", color="red")+
  stat_poly_eq(label.x = "right")+
  ggtitle("Richness (Coral)")

gg.obs.coral.site <- ggplot(df.div.coral,aes(x=site,y=Observed,color=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darkslategray3","darkslategray4","#000004"))+
  geom_jitter(alpha=0.5)+
  ylab("ASV richness")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.obs.coral.seas <- ggplot(df.div.coral,aes(x=season,y=Observed,color=season))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(position = position_jitterdodge(dodge.width=0.5, jitter.width=1),size=3, alpha=0.5,aes(shape=season,group=season))+
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  ylab("ASV richness")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.obs.coral.ss <- ggplot(df.div.coral,aes(x=symbstate,y=Observed,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("lightcyan3","coral4"))+
  geom_jitter(alpha=0.5)+
  ylab("ASV richness")+
  scale_x_discrete(name = NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.obs.coral.sd <- ggplot(df.div.coral,aes(x=density,y=Observed,color=density))+
  geom_point(size=3, alpha=0.8)+
  scale_color_continuous(high = "#132B43", low = "#6DCDFB")+
  theme_cowplot()+
  xlab("Density")+
  ylab("ASV richness")+
  labs(color="Density")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

gg.obs.coral.ss.site <- ggplot(df.div.coral,aes(x=site,y=Observed,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("ASV richness")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")


#ggsave(gg.obs.coral.site.ss,file="./figures/gg.obs.coral.site.ss.png",width=8,height=4)
#ggsave(gg.obs.coral.site.seas,file="./figures/gg.obs.coral.site.seas.png",width=8,height=4)
#ggsave(gg.obs.coral.sd,file="./figures/gg.obs.coral.sd.png",width=8,height=4)

#ggsave(gg.obs.coral.site,file="./figures/gg.obs.coral.site.pdf",width=8,height=4)
#ggsave(gg.obs.coral.seas,file="./figures/gg.obs.coral.seas.png",width=8,height=4)
#ggsave(gg.obs.coral.ss,file="./figures/gg.obs.coral.ss.pdf",width=8,height=4)
#ggsave(gg.obs.coral.sd,file="./figures/gg.obs.coral.sd.pdf",width=8,height=4)
#ggsave(gg.obs.coral.sd.sqrt,file="./figures/gg.obs.coral.sd.sqrt.png",width=8,height=4)
#ggsave(gg.obs.coral.ss.site,file="./figures/gg.obs.coral.ss.site.png",width=8,height=4)
```

### Evenness

```{r evenness coral}
gg.even.coral.site <- ggplot(df.div.coral,aes(x=site,y=even,color=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darkslategray3","darkslategray4","#000004"))+
  geom_jitter(alpha=0.5)+
  ylab("Evenness")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.even.coral.seas <- ggplot(df.div.coral,aes(x=season,y=even,color=season))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  geom_jitter(alpha=0.5)+
  ylab("Evenness")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.even.coral.ss <- ggplot(df.div.coral,aes(x=symbstate,y=even,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("lightcyan3","coral4"))+
  geom_jitter(alpha=0.5)+
  ylab("Evenness")+
  scale_x_discrete(name = NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.even.coral.sd <- ggplot(df.div.coral,aes(x=density,y=even,color=density))+
  geom_point(size=3, alpha=0.8)+
  scale_color_continuous(high = "#132B43", low = "#6DCDFB")+
  theme_cowplot()+
  xlab("Density")+
  ylab("Evenness")+
  labs(color="Density")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

gg.even.coral.ss.site <- ggplot(df.div.coral,aes(x=site,y=even,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("Evenness")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")

#ggsave(gg.even.coral.site,file="./figures/gg.even.coral.site.pdf",width=8,height=4)
#ggsave(gg.even.coral.seas,file="./figures/gg.even.coral.seas.pdf",width=8,height=4)
#ggsave(gg.even.coral.ss,file="./figures/gg.even.coral.ss.pdf",width=8,height=4)
#ggsave(gg.even.coral.sd,file="./figures/gg.even.coral.sd.pdf",width=8,height=4)
#ggsave(gg.even.coral.ss.site,file="./figures/gg.even.coral.ss.site.pdf",width=8,height=4)
```



### Faith's D Plots {.tabset}

#### Figures

```{r faiths d}
#df.div.coral.pd <- subset(df.div.pd, type=="coral")

gg.fd.site.alltypes <-ggplot(df.div.pd,aes(x=type,y=PD,color=type))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","SW","Sed."))+
  geom_jitter(alpha=0.5)+
  ylab("Faith's D")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  facet_wrap(~forcats::fct_relevel(site, "NR", "RI", "CL"))

gg.fd.seas.alltypes <-ggplot(df.div.pd,aes(x=type,y=PD,color=type))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darksalmon","paleturquoise3","chocolate4"))+
  scale_x_discrete(labels=c("Coral","SW","Sed."))+
  geom_jitter(alpha=0.5)+
  ylab("Faith's D")+
  labs(x=NULL)+
  theme_cowplot()+ 
  theme(legend.position="none")+
  facet_wrap(~forcats::fct_relevel(season, "Summer","Fall"))

#setwd("~/oculina/diversity")
#ggsave(gg.fd.site.alltypes,file="./figures/gg.fd.site.alltypes.png",width=8,height=4)
#ggsave(gg.fd.seas.alltypes,file="./figures/gg.fd.seas.alltypes.png",width=8,height=4)


### Coral only

gg.fd.coral.site <- ggplot(df.div.pd.coral,aes(x=site,y=PD,color=site))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("darkslategray3","darkslategray4","#000004"))+
  geom_jitter(alpha=0.5)+
  ylab("Faith's D")+
  xlab("Site")+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.fd.coral.symb <- ggplot(df.div.pd.coral,aes(x=symbstate,y=PD,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("lightcyan3","coral4"))+
  geom_jitter(alpha=0.5)+
  ylab("Faith's D")+
  scale_x_discrete(name = NULL)+
  theme_cowplot()+
  theme(legend.position="none")+
  ggtitle("Coral")

gg.fd.coral.seas <- ggplot(df.div.pd.coral,aes(x=symbstate,y=PD,color=season))+
  geom_boxplot(outlier.shape=NA)+
  scale_color_manual(values=c("#ED7953FF","#8405A7FF"))+
  #geom_jitter(alpha=0.5)+
  ylab("Faith's D")+
  xlab("Site")+
  theme_cowplot()+
  ggtitle("Coral")
  #theme(legend.position="none")

gg.fd.coral.sd <- ggplot(df.div.coral.pd,aes(x=density,y=PD, color=site))+
  geom_point(size=3, aes(shape=symbstate))+
  scale_color_manual(values=c("#000004","darkslategray4","darkslategray3"))+
  scale_shape_manual(values=c(10, 19))+
  theme_cowplot()+
  xlab("Density (cells/cm2)")+
  ylab("Faith's D")+
  labs(shape="Symbiotic state",color="Site")+
 # theme(legend.position="none")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  geom_smooth(method=lm, se=FALSE, size=0.4, linetype="solid")+
  stat_poly_eq(label.x = "right")+
  ggtitle("Phylogenetic Diversity (Coral)")

gg.fd.coral.ss.site <- ggplot(df.div.pd.coral,aes(x=site,y=PD,color=symbstate))+
  geom_boxplot(outlier.shape=NA)+
  geom_point(aes(color=symbstate), size = 2, alpha = 0.3, position=position_jitterdodge(jitter.width=0.2)) +
  scale_colour_manual(values=c("lightcyan3","coral4")) +
  ylab("Faith's D")+
  xlab("Site")+
  labs(color = "Symbiotic State")+
  theme_cowplot() +
  scale_x_discrete(limits=c('NR','RI', 'CL'))+
  ggtitle("Coral")
  #theme(legend.position="none")


#ggsave(gg.fd.coral.site,file="./figures/gg.fd.coral.site.png",width=8,height=4)
#ggsave(gg.fd.coral.symb,file="./figures/gg.fd.coral.symb.png",width=8,height=4)
#ggsave(gg.fd.coral.seas,file="./figures/gg.fd.coral.seas.png",width=8,height=4)
#ggsave(gg.fd.coral.sd,file="./figures/gg.fd.coral.sd.png",width=8,height=4)
#ggsave(gg.fd.coral.ss.site,file="./figures/gg.fd.coral.ss.site.png",width=8,height=4)

```


## Playing with microshades
```{r microshades setup}
#remotes::install_github("KarstensLab/microshades")
library("microshades")
#remotes::install_github("mikemc/speedyseq")
library("speedyseq")

#all
#ps_glom <- tax_glom(ps.less, "Genus")
#ps0 <- transform_sample_counts(ps_glom, function(x) x / sum(x))
#ps1 <- merge_samples(ps0, "fullname")
#ps.all <- transform_sample_counts(ps1, function(x) x / sum(x))

#reorder sites
sample_data(ps.less)$site <- factor(sample_data(ps.less)$site, levels=c("NR","RI","CL"))
levels(sample_data(ps.less)$site)


# Use microshades function prep_mdf to agglomerate, normalize, and melt the phyloseq object
mdf.prep.less <- prep_mdf(ps.less, subgroup_level="Genus")

# Create a color object for the specified data
color.obj.less<- create_color_dfs(mdf.prep.less, group_level = "Phylum", subgroup_level = "Genus", cvd = TRUE)

# Extract
mdf.less <- color.obj.less$mdf
cdf.less <- color.obj.less$cdf

```

```{r facet wrap}
# remove current Sample column (currently a repeat of id), and then rename fullname = Sample
#library(dplyr)
mdf.less <- mdf.less %>%
  select(-Sample) %>%
  rename(Sample = fullname) %>%
  rename(number = sample)

new.sample.order <- reorder_samples_by(mdf.less, cdf.less, group_level = "Phylum", subgroup_level = "Family", sink_abundant_groups = FALSE)

mdf.new.sample.order <-new.sample.order$mdf
cdf.new.sample.order <-new.sample.order$cdf

plot.less <- plot_microshades(mdf.new.sample.order, cdf.new.sample.order, group_label = "Phylum Family")

ms.allsamples <- plot.less + 
  theme(legend.key.size = unit(0.5, "cm"), text=element_text(size=8)) +
  theme(axis.text.x = element_text(size= 6)) +
  facet_grid(~type, scales = "free_x", space="free") +
  theme (strip.text.x = element_text(size = 10))+
  theme(axis.title=element_text(size=10))+
  scale_y_continuous(labels = scales::percent, expand = expansion(0))
#can't figure out how to reorder samples to be NR-RI-CL :/
  
#ggsave(ms.allsamples,file="./figures/ms.allsamples.png",width=12,height=6)
```

```{r microshades plot coral only}
ps.coral <- subset_samples(ps.less, type=="coral")
#make site a factor
sample_data(ps.coral)$site <- as.factor(sample_data(ps.coral)$site)
mdf.coral <- prep_mdf(ps.coral, subgroup_level="Genus")
color.obj.coral<- create_color_dfs(mdf.coral, group_level = "Phylum", subgroup_level = "Genus", cvd = TRUE)

mdf.coral <- color.obj.coral$mdf
cdf.coral <- color.obj.coral$cdf

mdf.coral <- mdf.coral %>%
  select(-Sample) %>%
  rename(Sample = fullname) %>%
  rename(number = sample)

new.sample.order <- reorder_samples_by(mdf.coral, cdf.coral, group_level = "Phylum", subgroup_level = "Family", sink_abundant_groups = TRUE)

mdf.new.sample.order <-new.sample.order$mdf
cdf.new.sample.order <-new.sample.order$cdf

plot.coral <- plot_microshades(mdf.new.sample.order, cdf.new.sample.order, group_label = "Phylum Family")

ms.coral.site <- plot.coral + 
  theme(legend.key.size = unit(0.5, "cm"), text=element_text(size=8)) +
  theme(axis.text.x = element_text(size= 6)) +
  theme (strip.text.x = element_text(size = 10))+
  theme(axis.title=element_text(size=10))+
  scale_y_continuous(labels = scales::percent, expand = expansion(0))+
  facet_grid(~factor(site, levels=c("NR","RI","CL")), scales = "free_x", space="free")

ms.coral.site
#ggsave(ms.coral.site,file="./figures/ms.coral.site.png",width=12,height=6)
```

```{r microshades by all_id}
ps_glom.less <- tax_glom(ps.less, "Genus")
ps0.less <- transform_sample_counts(ps_glom.less, function(x) x / sum(x))
ps1.less <- merge_samples(ps0.less, "all_id")
ps.less.allid <- transform_sample_counts(ps1.less, function(x) x / sum(x))


# Use microshades function prep_mdf to agglomerate, normalize, and melt the phyloseq object
mdf.prep.allid <- prep_mdf(ps.less.allid, subgroup_level="Genus")

# Create a color object for the specified data
color.obj.allid<- create_color_dfs(mdf.prep.allid, group_level = "Phylum", subgroup_level = "Genus", cvd = TRUE)

# Extract
mdf.allid <- color.obj.allid$mdf
cdf.allid <- color.obj.allid$cdf

#sink abundant groups
new.sample.order <- reorder_samples_by(mdf.allid, cdf.allid, group_level = "Phylum", subgroup_level = "Family", sink_abundant_groups = TRUE)

mdf.new.sample.order <-new.sample.order$mdf
cdf.new.sample.order <-new.sample.order$cdf


plot.allid <- plot_microshades(mdf.new.sample.order, cdf.new.sample.order, group_label = "Phylum Family")


ms.allid <- plot.allid + 
  theme(legend.key.size = unit(0.5, "cm"), text=element_text(size=8)) +
  theme(axis.text.x = element_text(size= 6)) +
  theme (strip.text.x = element_text(size = 10))+
  theme(axis.title=element_text(size=10))+
  scale_y_continuous(labels = scales::percent, expand = expansion(0))

#ggsave(ms.allid,file="./figures/ms.allid.png",width=12,height=6)

```

```{r microshades initial plots}
plot1 <- plot_microshades(mdf, cdf, group_label = "Phylum Genus")
plot1.all <- plot_microshades(mdf.less, cdf.less, group_label = "Phylum Family")
plot1.all.type <- plot_microshades(mdf.less.type, cdf.less.type, group_label = "Phylum Family")
plot1.site <- plot_microshades(mdf.coral.site, cdf.coral.site, group_label = "Phylum Family")
plot1.season <- plot_microshades(mdf.coral.season, cdf.coral.season, group_label = "Phylum Family")
plot1.symbstate <- plot_microshades(mdf.coral.symbstate, cdf.coral.symbstate, group_label = "Phylum Family")

```

```{r all samples reordered by group}
# reorder_samples_by will change the order of samples based on an abundance of a specified subgroup taxonomy
new.sample.order <- reorder_samples_by(mdf, cdf, order = "Thiovulum", group_level = "Phylum", subgroup_level = "Genus", sink_abundant_groups = TRUE)

mdf.new.sample.order <-new.sample.order$mdf
cdf.new.sample.order <-new.sample.order$cdf

plot_2 <- plot_microshades(mdf.new.sample.order, cdf.new.sample.order, group_label = "Phylum Family")

plot_2 + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
  theme(legend.key.size = unit(0.2, "cm"), text=element_text(size=10)) +
  theme(axis.text.x = element_text(size= 6))
```

```{r all_id reordered by group}
# reorder_samples_by will change the order of samples based on an abundance of a specified subgroup taxonomy
new.sample.order.coral <- reorder_samples_by(mdf.rare, cdf.rare, order = "Cyanobium_PCC-6307", group_level = "Phylum", subgroup_level = "Genus", sink_abundant_groups = TRUE)

mdf.new.sample.order <-new.sample.order.coral$mdf
cdf.new.sample.order <-new.sample.order.coral$cdf

plot_2 <- plot_microshades(mdf.new.sample.order, cdf.new.sample.order, group_label = "Phylum Genus")

plot_2 + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
  theme(legend.key.size = unit(0.2, "cm"), text=element_text(size=10)) +
  theme(axis.text.x = element_text(size= 6))
```

```{r reorder samples by abundance of group levels only}
# reorder_samples_by will change the order of samples based on an abundance of a specified subgroup taxonomy
# The default subgroup_level is "Genus" 
new.group.order <- reorder_samples_by(mdf.less, cdf.less, group_level = "Phylum", subgroup_level = "Family", sink_abundant_groups = TRUE)

mdf.new.group.order <-new.group.order$mdf
cdf.new.group.order <-new.group.order$cdf

plot_3 <- plot_microshades(mdf.new.group.order, cdf.new.group.order, group_label = "Phylum Family")

plot_3 + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
  theme(legend.key.size = unit(0.2, "cm"), text=element_text(size=10)) +
  theme(axis.text.x = element_text(size= 6))
```

```{r}
# reorder_samples_by will change the order of samples based on Family an abundance of a group and reorder the Phylum to sink the most abundant groups
reordered <- reorder_samples_by(mdf.rare, cdf.rare, order = "Other", group_level = "Phylum", subgroup_level = "Family",sink_abundant_groups=TRUE)

mdf.reordered <-reordered$mdf
cdf.reordered <-reordered$cdf

plot_3 <- plot_microshades(mdf.reordered, cdf.reordered, group_label = "Phylum Family")

plot_3 + scale_y_continuous(labels = scales::percent, expand = expansion(0)) +
  theme(legend.key.size = unit(0.2, "cm"), text=element_text(size=10)) +
  theme(axis.text.x = element_text(size= 6))
```






