---
title: "oculina16s_analysis_raw"
output:
  word_document: default
  html_document: default
date: '2022-08-17'
---
### Based on DADA2 Pipeline 1.16 Walkthrough & Nicola Kriefall's Moorea holobiont analysis

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

## Packages
```{r packages}
library(ggplot2)
library(cowplot)
library(phyloseq)
library(car)
library(ggpubr)
library(vegan)
library(dada2)
library(stats)
library(MuMIn)
library(sjPlot)
library(webshot)
```


## Read in data

```{r read in data}
#setwd("~/oculina/data/")
samdf <- read.csv("~/oculina/data/oculina16s_sampledata_symdens.csv",header=TRUE) row.names(samdf) <- samdf$id
load("~/oculina/data/taxa2.rev.Rdata")
```

## Phyloseq objects

```{r making phyloseq objects, eval=FALSE}
seqtab.less <- read.csv("~/oculina/data/oculina16s_rev_seqtab.less",row.names=1)
load("~/oculina/data/ps.less_rev.Rdata")
ps.less #7005 taxa, 71 samples
```

```{r}
#tried to do merge_phyloseq so that I could easily add new metadata but can't get it to work
#samdf.new <- read.csv("~/oculina/data/oculina16s_sampledata_symdens.csv")
#density.new <- samdf.new %>% select(id, density)
#samdf.sd <- density.new %>% rename(density.new = density)
#rownames(samdf.sd) <- samdf.new$id
#row.names.remove <- c("D6","H2","G9","F10","G10","H10")
#samdf.sd <- samdf.sd[!(row.names(samdf.sd) %in% row.names.remove), ]

#ps.less.new <- merge_phyloseq(ps.less, samdf.sd)
#head(sample_data(ps.less.new))
#samdf.less <- sample_data(ps.less.new)

#install.packages("arsenal")
#library("arsenal")

#summary(comparedf(samdf.sd, samdf.less))

```


# Diversity

[Notes from phyloseq author](https://rdrr.io/bioc/phyloseq/man/estimate_richness.html)
Visualize alpha-diversity - Should be done on raw, untrimmed dataset

```{r generate div metrics}
df <- data.frame(estimate_richness(ps.less, split=TRUE, measures=c("Shannon","Simpson", "InvSimpson","Observed")))
# NOTE: I get a warning that my data doesn't contain singletons, but this is untrimmed raw data, so I'm not sure why this is the case. I do not get this error when I use ps.rare, presumably because rarefying data caused some data to become singletons.
# NOTE from DADA2 creator: DADA2 does not call singletons, due to the difficulty of differentiating rare singleton errors from real singleton variants. This means you should not use the output of DADA2 to estimate richness (eg. Chao S1). However, you shouldn't have been doing that with the output of other methods either, as the high levels of FP singletons made richness estimates wrong anyway. Right now, I don't think a method exists that can make valid richness estimates from high-throughput amplicon data due to the difficulty of calling singletons accurately, and the sensitivity of richness estimation to the number of singletons. Other measures of diversity that aren't totally reliant on singletons, eg. Shannon/Simpson, are valid to use, and you can ignore the warning in phyloseq when calculating those measures.
# CONCLUSION: do not use Chao1 in analysis; Shannon and Simpson should be okay

df$id <- rownames(df)
df.div <- merge(df,samdf,by="id") #add sample data

#transform density
#library(e1071)
skewness(df.div.coral$density) #very right skewed (1.93)
df.div.coral$density_sqrt <- sqrt(df.div.coral$density)

#df.div$density <- as.numeric(df.div$density)
#df.div <- df.div %>% mutate(density_log = log(density))
#shannon diversity divided by species richness
df.div$even <- df.div$Shannon/(log(df.div$Observed))
df.div.NR <- subset(df.div,site=="NR")
df.div.RI <- subset(df.div,site=="RI")
df.div.CL <- subset(df.div,site=="CL")
df.div.summer <- subset(df.div,season=="Summer")
df.div.fall <- subset(df.div,season=="Fall")
df.div.coral <- subset(df.div, type=="coral")
df.div.ss <- subset(df.div, type=="sediment" | type =="seawater")
df.div.coral.NR <- subset(df.div.coral,site=="NR")
df.div.coral.RI <- subset(df.div.coral,site=="RI")
df.div.coral.CL <- subset(df.div.coral,site=="CL")
df.div.coral.NR.RI <- subset(df.div.coral,site %in% c("NR","RI"))
```

### GLMS - Alpha Diversity Indices

```{r compare types (coral, sed, sw)}
df.div$season <- as.factor(df.div$season)
df.div$site <- as.factor(df.div$site)
df.div$type <- as.factor(df.div$type)
df.div$density <- as.numeric(df.div$density)

str(df.div)

glm.0 <- glm(Shannon ~ 1, data=df.div, family=gaussian())
glm.1 <- glm(Shannon ~ type, data=df.div, family=gaussian)
glm.2 <- glm(Shannon ~ type + season + site, data=df.div, family=gaussian)
glm.3 <- glm(Shannon ~ type + season * site, data=df.div, family=gaussian)
glm.4 <- glm(Shannon ~ type * season + site, data=df.div, family=gaussian)
glm.5 <- glm(Shannon ~ type * season * site, data=df.div, family=gaussian)

AICc(glm.0, glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.1 is best model
summary(glm.1)
#             Estimate Std. Error t value Pr(>|t|)    
#(Intercept)    3.4760     0.1223  28.424  < 2e-16 ***
#typeseawater   0.3132     0.2583   1.213    0.229    
#typesediment   1.6119     0.2583   6.240 3.22e-08 ***

#calc diff in chi square statistics for null model and the model with independent variances (deviances) and dif in df
1-pchisq(71.991-45.761, 70-68)
#2.014781e-06 
#reject null hypothesis that there is no different b/w null and model with variables

tab_model(glm.1) #makes a nice looking table
tab_model(glm.1, file="./stats/sha.types.glm.gauss.html")

webshot("./stats/sha.types.glm.gauss.html", "./stats/sha.types.glm.gauss.png")


### Evenness - all types

glm.0 <- glm(even ~ 1, data=df.div, family=gaussian())
glm.1 <- glm(even ~ type, data=df.div, family=gaussian)
glm.2 <- glm(even ~ type + season + site, data=df.div, family=gaussian)
glm.3 <- glm(even ~ type + season * site, data=df.div, family=gaussian)
glm.4 <- glm(even ~ type * season + site, data=df.div, family=gaussian)
glm.5 <- glm(even ~ type * season * site, data=df.div, family=gaussian)

AICc(glm.0, glm.1, glm.2, glm.3, glm.4, glm.5)
# null model best


### Richness - all types

glm.0 <- glm(Observed ~ 1, data=df.div, family=gaussian())
glm.1 <- glm(Observed ~ type, data=df.div, family=gaussian)
glm.2 <- glm(Observed ~ type + season + site, data=df.div, family=gaussian)
glm.3 <- glm(Observed ~ type + season * site, data=df.div, family=gaussian)
glm.4 <- glm(Observed ~ type * season + site, data=df.div, family=gaussian)
glm.5 <- glm(Observed ~ type * season * site, data=df.div, family=gaussian)

AICc(glm.0, glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.2 best
summary(glm.2)

#             Estimate Std. Error t value Pr(>|t|)    
#(Intercept)   106.967     79.571   1.344    0.184    
#typeseawater  102.821     65.805   1.563    0.123    
#typesediment  360.062     65.530   5.495 7.01e-07 ***
#seasonSummer  -17.007     56.292  -0.302    0.764    
#siteNR         33.436     70.220   0.476    0.636    
#siteRI          9.301     71.097   0.131    0.896   

tab_model(glm.2)
```

```{r shannon glm coral}

# Notes on alpha diversity indices:
    # Shannon - measures richness, so how many different bacteria in each sample
    # Chao1 - richness can be sensitive to read depth; Chao1 has some corrections to overcome this
    # Simpson - measures probability of resampling the same species on two consecutive draws with replacement

df.div.coral$season <- as.factor(df.div.coral$season)
df.div.coral$season <- relevel(df.div.coral$season, ref="Summer")
df.div.coral$site <- as.factor(df.div.coral$site)
df.div.coral$site <- relevel(df.div.coral$site, ref="NR")
df.div.coral$density <- as.numeric(df.div.coral$density)
df.div.coral$density_sqrt <- sqrt(df.div.coral$density)
df.div.coral$density_sqrt <- as.numeric(df.div.coral$density_sqrt)
str(df.div.coral)

qqPlot(df.div.coral$Shannon)
shapiro.test(df.div.coral$Shannon) #normally distributed
ggdensity(df.div.coral$Shannon)

### GLM - Shannon ###
#using Gaussian distribution bc normal distribution

glm.0 <- glm(Shannon ~ 1, data=df.div.coral, family=gaussian())
glm.1 <- glm(Shannon ~ season+site+density, data=df.div.coral, family=gaussian())
glm.2 <- glm(Shannon ~ season+site*density, data=df.div.coral, family=gaussian())
glm.3 <- glm(Shannon ~ season*site+density, data=df.div.coral, family=gaussian())
glm.4 <- glm(Shannon ~ site+season*density, data=df.div.coral, family=gaussian())
glm.5 <- glm(Shannon ~ season*site*density, data=df.div.coral, family=gaussian())

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.2 best AIC, glm.5 very close
summary(glm.2)
#                 Estimate Std. Error t value Pr(>|t|)    
#(Intercept)     2.945e+00  2.510e-01  11.732 3.37e-14 ***
#seasonFall      2.671e-01  2.272e-01   1.175 0.247197    
#siteCL          8.518e-01  4.506e-01   1.890 0.066364 .  
#siteRI          6.510e-01  3.028e-01   2.150 0.038013 *  
#density         1.205e-07  3.159e-08   3.816 0.000486 ***
#siteCL:density -2.302e-07  5.150e-08  -4.470 6.85e-05 ***
#siteRI:density -1.461e-07  3.568e-08  -4.094 0.000213 ***

1-pchisq(29.785-15.253, 44-38)
#0.0242263 cool

#setwd("~/oculina/diversity/stats")
tab_model(glm.2)
tab_model(glm.2, file="./stats/sha.coral.glm.gauss.html")
#library(webshot)
webshot("./stats/sha.coral.glm.gauss.html", "./stats/sha.coral.glm.gauss.png")

# trying with sqrt-transformed density data

#df.div.coral$density_log <- as.numeric(df.div.coral$density_log)
#density_log <- df.div.coral$density_log
#density_log[is.infinite(density_log)] <- 0
#df.div.coral$density_log <- density_log

glm.0 <- glm(Shannon ~ 1, data=df.div.coral, family=gaussian())
glm.1 <- glm(Shannon ~ season+site+density_sqrt, data=df.div.coral, family=gaussian())
glm.2 <- glm(Shannon ~ season+site*density_sqrt, data=df.div.coral, family=gaussian())
glm.3 <- glm(Shannon ~ season*site+density_sqrt, data=df.div.coral, family=gaussian())
glm.4 <- glm(Shannon ~ site+season*density_sqrt, data=df.div.coral, family=gaussian())
glm.5 <- glm(Shannon ~ season*site*density_sqrt, data=df.div.coral, family=gaussian())

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.2 best AIC
summary(glm.2)
#                      Estimate Std. Error t value Pr(>|t|)    
#(Intercept)          2.6192306  0.3011504   8.697 1.42e-10 ***
#seasonFall           0.3074556  0.2174935   1.414 0.165611    
#siteCL               1.6891499  0.5996075   2.817 0.007646 ** 
#siteRI               1.1748559  0.3747495   3.135 0.003308 ** 
#density_sqrt         0.0004923  0.0001217   4.047 0.000246 ***
#siteCL:density_sqrt -0.0010198  0.0002223  -4.588 4.76e-05 ***
#siteRI:density_sqrt -0.0006796  0.0001524  -4.460 7.07e-05 ***

tab_model(glm.2, digits=4)
tab_model(glm.2, file="./stats/sha.coral.glm.gauss.sqrt.html")
#webshot("./stats/sha.coral.glm.gauss.sqrt.html", "./stats/sha.coral.glm.gauss.sqrt.png")
with(summary(glm.2), 1 - deviance/null.deviance) #0.5222778

#trying with symbstate instead of density:

glm.0 <- glm(Shannon ~ 1, data=df.div.coral, family=gaussian())
glm.1 <- glm(Shannon ~ season+site+symbstate, data=df.div.coral, family=gaussian())
glm.2 <- glm(Shannon ~ season+site*symbstate, data=df.div.coral, family=gaussian())
glm.3 <- glm(Shannon ~ season*site+symbstate, data=df.div.coral, family=gaussian())
glm.4 <- glm(Shannon ~ site+season*symbstate, data=df.div.coral, family=gaussian())
glm.5 <- glm(Shannon ~ season*site*symbstate, data=df.div.coral, family=gaussian())

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.2 best AIC
summary(glm.2)
#                           Estimate Std. Error t value Pr(>|t|)    
#(Intercept)                3.119842   0.268222  11.632 4.35e-14 ***
#seasonFall                 0.324202   0.244887   1.324  0.19345    
#siteRI                     0.611807   0.349167   1.752  0.08781 .  
#siteCL                    -0.003359   0.416604  -0.008  0.99361    
#symbstateSymbiotic         0.924520   0.356398   2.594  0.01340 *  
#siteRI:symbstateSymbiotic -1.567137   0.484216  -3.236  0.00251 ** 
#siteCL:symbstateSymbiotic -1.268982   0.574674  -2.208  0.03334 *  

tab_model(glm.2, digits=4)
tab_model(glm.2, file="./stats/sha.coral.glm.gauss.sqrt.html")
#webshot("./stats/sha.coral.glm.gauss.sqrt.html", "./stats/sha.coral.glm.gauss.sqrt.png")
```


```{r GLM Evenness}
## GLM - Evenness ###
qqPlot(df.div.coral$even)
shapiro.test(df.div.coral$even) #p=0.045
ggdensity(df.div.coral$even) #left skewed?


glm.0 <- glm(even ~ 1, data=df.div.coral, family=Gamma())
glm.1 <- glm(even ~ season+site+density_sqrt, data=df.div.coral, family=Gamma())
#summary(glm.1)
glm.2 <- glm(even ~ season+site*density_sqrt, data=df.div.coral, family=Gamma())
#summary(glm.2)
glm.3 <- glm(even ~ season*site+density_sqrt, data=df.div.coral, family=Gamma())
#summary(glm.3)
glm.4 <- glm(even ~ site+season*density_sqrt, data=df.div.coral, family=Gamma())
#summary(glm.4)
glm.5 <- glm(even ~ season*site*density_sqrt, data=df.div.coral, family=Gamma())
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.0 (Null model!) is best with both gaussian and gamma
summary(glm.0) #so none of the variables are predictive of evenness?

#for glm.5:
#Coefficients: (2 not defined because of singularities)
#^^^why does this happen?! i think bc of CL...can I change CL to not be intercept?



glm.0 <- glm(even ~ 1, data=df.div.coral, family=Gamma())
glm.1 <- glm(even ~ season+site+symbstate, data=df.div.coral, family=Gamma())
#summary(glm.1)
glm.2 <- glm(even ~ season+site*symbstate, data=df.div.coral, family=Gamma())
#summary(glm.2)
glm.3 <- glm(even ~ season*site+symbstate, data=df.div.coral, family=Gamma())
#summary(glm.3)
glm.4 <- glm(even ~ site+season*symbstate, data=df.div.coral, family=Gamma())
#summary(glm.4)
glm.5 <- glm(even ~ season*site*symbstate, data=df.div.coral, family=Gamma())
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5) #glm.5 actually best by a smidgen...

summary(glm.5)
```



```{r GLM richness}
## GLM - richness ###
qqPlot(df.div.coral$Observed) # discrete, not continuous
shapiro.test(df.div.coral$Observed) #really sig/not normal
ggdensity(df.div.coral$Observed) #right skewed

#using poisson because counts; however, poisson is sensitive to assumption that mean is equal to variance; alternative is quasi-poisson or negative binomial
glm.0 <- glm(Observed ~ 1, data=df.div.coral, family=poisson())
glm.1 <- glm(Observed ~ season+site+density, data=df.div.coral, family=poisson())
#summary(glm.1)
glm.2 <- glm(Observed ~ season+site*density, data=df.div.coral, family=poisson())
#summary(glm.2)
glm.3 <- glm(Observed ~ season*site+density, data=df.div.coral, family=poisson())
#summary(glm.3)
glm.4 <- glm(Observed ~ site+season*density, data=df.div.coral, family=poisson())
#summary(glm.4)
glm.5 <- glm(Observed ~ season*site*density, data=df.div.coral, family=poisson())
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.5 is best
summary(glm.5) 

#for glm.5:
#Coefficients: (2 not defined because of singularities)
#^^^why does this happen?! i think bc of CL...can I change CL to not be intercept?


# trying negative binomial
library(MASS)
glm.0 <- glm.nb(Observed ~ 1, data=df.div.coral)
glm.1 <- glm.nb(Observed ~ season+site+density, data=df.div.coral)
#summary(glm.1)
glm.2 <- glm.nb(Observed ~ season+site*density, data=df.div.coral)
#summary(glm.2)
glm.3 <- glm.nb(Observed ~ season*site+density, data=df.div.coral)
#summary(glm.3)
glm.4 <- glm.nb(Observed ~ site+season*density, data=df.div.coral)
#summary(glm.4)
glm.5 <- glm.nb(Observed ~ season*site*density, data=df.div.coral)
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.5 best by a hair
summary(glm.5)
#                              Estimate Std. Error z value Pr(>|z|)    
#(Intercept)                  5.628e+00  3.992e-01  14.099  < 2e-16 ***
#seasonSummer                -4.553e-01  2.908e-01  -1.566 0.117439    
#siteNR                      -2.112e+00  4.855e-01  -4.351 1.35e-05 ***
#siteRI                      -5.848e-01  3.449e-01  -1.696 0.089948 .  
#density                     -1.886e-07  5.272e-08  -3.578 0.000347 ***
#seasonSummer:siteNR          1.521e+00  4.597e-01   3.309 0.000936 ***
#seasonSummer:siteRI                 NA         NA      NA       NA    
#seasonSummer:density         7.328e-08  4.319e-08   1.697 0.089752 .  
#siteNR:density               3.343e-07  6.399e-08   5.224 1.75e-07 ***
#siteRI:density               9.053e-08  3.325e-08   2.723 0.006476 ** 
#seasonSummer:siteNR:density -1.338e-07  6.390e-08  -2.095 0.036214 *  
#seasonSummer:siteRI:density         NA         NA      NA       NA   


### with sqrt density

glm.0 <- glm.nb(Observed ~ 1, data=df.div.coral)
glm.1 <- glm.nb(Observed ~ season+site+density_sqrt, data=df.div.coral)
#summary(glm.1)
glm.2 <- glm.nb(Observed ~ season+site*density_sqrt, data=df.div.coral)
#summary(glm.2)
glm.3 <- glm.nb(Observed ~ season*site+density_sqrt, data=df.div.coral)
#summary(glm.3)
glm.4 <- glm.nb(Observed ~ site+season*density_sqrt, data=df.div.coral)
#summary(glm.4)
glm.5 <- glm.nb(Observed ~ season*site*density_sqrt, data=df.div.coral)
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.2 best with sqrt
summary(glm.2)
#                      Estimate Std. Error z value Pr(>|z|)    
#(Intercept)          3.909e+00  2.423e-01  16.130  < 2e-16 ***
#seasonFall          -1.973e-01  1.734e-01  -1.138 0.255077    
#siteCL               1.805e+00  4.779e-01   3.778 0.000158 ***
#siteRI               1.297e+00  3.012e-01   4.307 1.66e-05 ***
#density_sqrt         4.820e-04  9.724e-05   4.957 7.17e-07 ***
#siteCL:density_sqrt -1.035e-03  1.781e-04  -5.810 6.26e-09 ***
#siteRI:density_sqrt -7.518e-04  1.224e-04  -6.144 8.06e-10 ***

tab_model(glm.2, digits=4)


glm.0 <- glm.nb(Observed ~ 1, data=df.div.coral)
glm.1 <- glm.nb(Observed ~ season+site+symbstate, data=df.div.coral)
#summary(glm.1)
glm.2 <- glm.nb(Observed ~ season+site*symbstate, data=df.div.coral)
#summary(glm.2)
glm.3 <- glm.nb(Observed ~ season*site+symbstate, data=df.div.coral)
#summary(glm.3)
glm.4 <- glm.nb(Observed ~ site+season*symbstate, data=df.div.coral)
#summary(glm.4)
glm.5 <- glm.nb(Observed ~ season*site*symbstate, data=df.div.coral)
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5) #null model best - weird

```

```{r GLM Simpson}
## GLM - Simpson ###
qqPlot(df.div.coral$Simpson)
shapiro.test(df.div.coral$Simpson) #not normally distributed
ggdensity(df.div.coral$Simpson) #very left skewed

#maybe should use gamma? https://stats.stackexchange.com/questions/190763/how-to-decide-which-glm-family-to-use


glm.0 <- glm(Simpson ~ 1, data=df.div.coral, family=Gamma())
glm.1 <- glm(Simpson ~ season+site+density, data=df.div.coral, family=Gamma())
#summary(glm.1)
glm.2 <- glm(Simpson ~ season+site*density, data=df.div.coral, family=Gamma())
#summary(glm.2)
glm.3 <- glm(Simpson ~ season*site+density, data=df.div.coral, family=Gamma())
#summary(glm.3)
glm.4 <- glm(Simpson ~ site+season*density, data=df.div.coral, family=Gamma())
#summary(glm.4)
glm.5 <- glm(Simpson ~ season*site*density, data=df.div.coral, family=Gamma())
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.4 is best, glm.0 close second
summary(glm.4) #for gamma
#                       Estimate Std. Error t value Pr(>|t|)    
#(Intercept)           1.138e+00  4.941e-02  23.031   <2e-16 ***
#siteNR               -9.423e-02  4.100e-02  -2.298   0.0270 *  
#siteRI               -7.796e-02  4.187e-02  -1.862   0.0702 .  
#seasonSummer          3.905e-02  4.249e-02   0.919   0.3637    
#density              -1.525e-09  5.020e-09  -0.304   0.7629    
#seasonSummer:density  2.289e-09  5.575e-09   0.411   0.6836   

#library(lmtest)
#check for heteroskedasticity
bptest(glm.4)
```

```{r GLM InvSimpson}
## GLM - InvSimpson ###
qqPlot(df.div.coral$InvSimpson)
shapiro.test(df.div.coral$InvSimpson) #not normally distributed
ggdensity(df.div.coral$InvSimpson) #very right skewed - I think gamma best

#models:
glm.0 <- glm(InvSimpson ~ 1, data=df.div.coral, family=Gamma())
glm.1 <- glm(InvSimpson ~ season+site+density, data=df.div.coral, family=Gamma())
#summary(glm.1)
glm.2 <- glm(InvSimpson ~ season+site*density, data=df.div.coral, family=Gamma())
#summary(glm.2)
glm.3 <- glm(InvSimpson ~ season*site+density, data=df.div.coral, family=Gamma())
#summary(glm.3)
glm.4 <- glm(InvSimpson ~ site+season*density, data=df.div.coral, family=Gamma())
#summary(glm.4)
glm.5 <- glm(InvSimpson ~ season*site*density, data=df.div.coral, family=Gamma())
#summary(glm.5)

AICc(glm.1, glm.2, glm.3, glm.4, glm.5)
# glm.2 best
summary(glm.2)
#                 Estimate Std. Error t value Pr(>|t|)    
#(Intercept)     1.110e-02  1.671e-02   0.664 0.510461    
#seasonSummer    1.016e-02  7.965e-03   1.276 0.209730    
#siteNR          5.823e-02  2.197e-02   2.650 0.011670 *  
#siteRI          1.202e-02  1.708e-02   0.704 0.485868    
#density         1.101e-08  3.793e-09   2.904 0.006115 ** 
#siteNR:density -1.536e-08  4.052e-09  -3.790 0.000523 ***
#siteRI:density -8.700e-09  3.985e-09  -2.183 0.035290 *   

#Coefficients: (2 not defined because of singularities)
#^^^Why?!
```

```{r GLM excluding CL - sanity check?}
df.div.coral.NR.RI$season <- as.factor(df.div.coral.NR.RI$season)
df.div.coral.NR.RI$site <- as.factor(df.div.coral.NR.RI$site)
df.div.coral.NR.RI$density <- as.numeric(df.div.coral.NR.RI$density)
str(df.div.coral.NR.RI)

glm.0 <- glm(Shannon ~ 1, data=df.div.coral.NR.RI, family=gaussian())
glm.1 <- glm(Shannon ~ season+site+density, data=df.div.coral.NR.RI, family=gaussian())
#summary(glm.1)
glm.2 <- glm(Shannon ~ season+site*density, data=df.div.coral.NR.RI, family=gaussian())
#summary(glm.2)
glm.3 <- glm(Shannon ~ season*site+density, data=df.div.coral.NR.RI, family=gaussian())
#summary(glm.3)
glm.4 <- glm(Shannon ~ site+season*density, data=df.div.coral.NR.RI, family=gaussian())
#summary(glm.4)
glm.5 <- glm(Shannon ~ season*site*density, data=df.div.coral.NR.RI, family=gaussian())
#summary(glm.5)

AICc(glm.0,glm.1, glm.2, glm.3, glm.4, glm.5)
#glm.2 best model (still! woo!)

summary(glm.2)
#                Estimate Std. Error t value Pr(>|t|)    
#(Intercept)     3.211662   0.271487  11.830 7.97e-13 ***
#seasonSummer   -0.267047   0.227255  -1.175 0.249198    
#siteRI          0.650927   0.302829   2.149 0.039783 *  
#density         0.018828   0.004934   3.816 0.000632 ***
#siteRI:density -0.022815   0.005573  -4.094 0.000295 ***
```

